site_name: Mad-Pascal
site_author: TeBe
site_description: "Mad-Pascal Dokumentacja"
site_keyword: "cross-compiler"

repo_url: https://github.com/tebe6502/mad-pascal-mkdocs/
edit_uri: main/docs/

theme:
    name: readthedocs
    hljs_languages:
        - delphi

nav:
    - Wprowadzenie: wprowadzenie.md
    - Mapa pamięci: mapa.md
    - Sposób użycia: sposob-uzycia.md
    - Składnia: skladnia.md
    - Stałe: stale.md
    - Typy: typy.md
    - Zmienne: zmienne.md
    - Instrukcje: instrukcje.md
    - Programy, moduły, biblioteki: moduly.md
    - Procedury, funkcje, modyfikatory: procedury-funkcje.md
    - Makra: makra.md
    - Wstawki assemblera: asm.md
    - Pliki zasobów: zasoby.md
    - Obsługa przerwań: przerwania.md
    - Operacje na plikach: pliki.md
    - Alternatywa dla DOS-a: ados.md
    - Biblioteki podstawowe: biblioteki-podstawowe.md
    - Porady: porady.md
    - Przykłady: przyklady.md
    - Projekty: projekty.md
