site_name: Mad-Pascal
site_author: TeBe
site_description: "Mad-Pascal Dokumentacja"
site_keyword: "cross-compiler"

repo_url: https://github.com/tebe6502/Mad-Pascal

theme:
    name: readthedocs
    hljs_languages:
        - delphi

nav:
    - Wprowadzenie: wprowadzenie.md
    - Mapa pamięci: mapa.md
    - Sposób użycia: sposob-uzycia.md
    - Składnia: skladnia.md
    - Wstawki assemblera: asmblock.md
    - Pliki zasobów: zasoby.md
    - Typy: typy.md
    - Stałe: stale.md
    - Zmienne: zmienne.md
    - Instrukcje: instrukcje.md
    - Procedury, funkcje, modyfikatory: procedury-funkcje.md
    - Obsługa przerwań: przerwania.md
    - Moduły: moduly.md
    - Biblioteki podstawowe: biblioteki-podstawowe.md
    - Porady: tricks.md
    - Przykłady: przyklady.md
    - Projekty: projekty.md
